#!/usr/bin/env bash
# Generate stable secrets once, into .secrets.yml (git-ignored). Re-running keeps
# the existing values — critical for ENCRYPTION_KEY, which must never change or
# every past draw becomes undecryptable.
set -euo pipefail
cd "$(dirname "$0")"

OUT=.secrets.yml
if [[ -f "$OUT" ]]; then
  echo "$OUT already exists — keeping existing secrets (good: the encryption key must be stable)."
  exit 0
fi

ENC=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))" 2>/dev/null \
      || openssl rand -base64 32)
PGPW=$(node -e "console.log(require('crypto').randomBytes(18).toString('hex'))" 2>/dev/null \
      || openssl rand -hex 18)

cat > "$OUT" <<EOF
# Git-ignored. Generated by gen-secrets.sh. BACK THIS UP — losing encryption_key
# loses every draw and the no-repeat history.
encryption_key: "${ENC}"
postgres_password: "${PGPW}"
# If you use SMTP, put the password here:
smtp_password: ""
EOF
chmod 600 "$OUT"
echo "Wrote $OUT. Back it up somewhere safe (separate from the database)."
